using System.Web.UI;

[assembly: WebResource("Zeus.Web.Resources.ColorPicker.blank.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_overlay.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_select.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.colorpicker_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_background.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hex.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_h.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_hsb_s.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_indic.gif", "image/gif")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_b.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_g.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_rgb_r.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.custom_submit.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.select2.png", "image/png")]
[assembly: WebResource("Zeus.Web.Resources.ColorPicker.slider.png", "image/png")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.css", "text/css", PerformSubstitution = true)]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.colorpicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.Plugins.jquery.timePicker.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.jQuery.jquery.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.TimePicker.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.core.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.sortable.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.jQuery.ui.tabs.js", "text/javascript")]


[assembly: WebResource("Zeus.Web.Resources.Select2.js.select2.min.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.Select2.css.select2.min.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.DnDUpload.DndUpload.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.DnDUpload.DndStyle.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.Dropzone.dropzone.min.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.Dropzone.dropzone.min.css", "text/css")]
[assembly: WebResource("Zeus.Web.Resources.Dropzone.dropzone.custom.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.Cropper.cropper.min.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.Cropper.cropper.min.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.ImageEditor.image-editor.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.ImageEditor.image-editor.css", "text/css")]

[assembly: WebResource("Zeus.Web.Resources.xregexp-unicode-base.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.xregexp-unicode-categories.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.xregexp.js", "text/javascript")]
[assembly: WebResource("Zeus.Web.Resources.xregexp.min.js", "text/javascript")]